### ISSUE TITLE
(chore) rewrite api for microservices, hateoas, and openapi standards.

### ISSUE THREAD

**Issue by denzuko** [denzuko/AIMS#5]
As a developer
I would like to implement new features more rapidly
So that my users can leverage my tools with faster life cycles

As a user
I would like to have better support for my cloud usage
So that I can implement AIMS in multiple sites.

As a third-party developer
I would like to implement tools on top of a standardized documented api that one can trust 
So that I can build Progressive Web UI
And So that I can build dashboards
And So that I can build automation tools

- [x] Should use support hateoas microservice api (python eve)
- [x] Should use support openapi standards (eve-swagger)
- [x] Should use redis as cache and ipc
- [x] Should use mongodb as backend
- [x] Should not introduce security issues
- [x] Should leverage openfaas and docker swarm for clustering and task management
- [x] Should support jwt authentication (eve-auth-jwt)
- [ ] Should have scheduled faas ansible tasks to gather facts into redis
- [ ] Should have standard set of deployers (heroku, docker image, terraform for multicloud, portainer stack)

**Comment by alexellis** [comment]
👍 how did this go? Do you have any questions on OpenFaaS?
